QOL

diff --git a/_meta/docker/Dockerfile.dev b/_meta/docker/Dockerfile.dev
--- a/_meta/docker/Dockerfile.dev
+++ b/_meta/docker/Dockerfile.dev
@@ -15,8 +15,7 @@ RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
     pipx \
     python3-colcon-common-extensions \
     python3-rosdep \
-    docker.io \
-    && rm -rf /var/lib/apt/lists/*
+    sudo
 
 RUN pipx install git+https://github.com/voshch/vcstool.git
 
@@ -43,12 +42,34 @@ COPY --from=python_deps --chown=${uid}:${gid} /opt/venv /opt/venv
 COPY --from=python_deps /usr/local/bin/uv /usr/local/bin/uv
 
 
+# install docker cli
+RUN  --mount=type=cache,target=/var/cache/apt,sharing=locked \
+    --mount=type=cache,target=/var/lib/apt,sharing=locked \
+    apt-get update && apt-get install -y \
+        ca-certificates \
+        curl \
+        gnupg \
+        lsb-release \
+    && install -m 0755 -d /etc/apt/keyrings \
+        && curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc \
+        && chmod a+r /etc/apt/keyrings/docker.asc \
+    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
+        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
+        | tee /etc/apt/sources.list.d/docker.list > /dev/null \
+    && apt-get update && apt-get install -y docker-ce-cli \
+    && rm -rf /var/lib/apt/lists/*
+
+
+
+
+# set user perms
 RUN (getent passwd ${uid} && userdel -rf $(getent passwd ${uid} | cut -d: -f1)) 2>/dev/null || true && \
     (getent group ${gid} && groupdel -f $(getent group ${gid} | cut -d: -f1)) 2>/dev/null || true && \
     groupadd -g ${gid} ${group} && \
     useradd -m -u ${uid} -g ${gid} -s /bin/bash ${username} && \
     passwd -d ${username} && \
-    usermod -aG docker ${username} && \
+    passwd -d root && \
+    groupadd -r sudo || true && \
     usermod -aG sudo ${username}
 
 WORKDIR /opt/arena_ws
@@ -63,3 +84,7 @@ COPY --chown=${uid}:${gid} src/Arena/_meta/docker/source.container source.contai
 RUN chmod +x /entrypoint.sh
 USER ${username}
 ENTRYPOINT ["/entrypoint.sh"]
+
+
+# cleanup
+# RUN rm -rf /var/lib/apt/lists/*
